baseurl: "/API-standaarden-voor-klantinteracties"
apiname: "API-standaarden voor klantinteracties"
url: "http://localhost:4000"
# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld.
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt geopend.
nav:
  - title: Klantinteracties
    subnav:
#      - title: Project
#        path: /
#      - title: Productvisie
#        path: /
#      - title: Architectuur
#        path: /
  - title: Informatiemodel
    subnav:
#      - title: Klanten
#        path: /
#      - title: Contactmomenten
#        path: /
#      - title: Productaanvragen
#        path: /
  - title: API-standaarden
    subnav:
      - title: Klanten API
        path: /API-standaarden/klanten-API-standaard
#      - title: Inzage API
#        path: /api-read
#      - title: Referentieimplementatie
#        path: /referentieimplementatie

plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

github: hdksi/API-standaarden-voor-klantinteracties

theme: jekyll-theme-cayman

remote_theme: VNG-Realisatie/jekyll-theme-vng-realisatie

project_name: API-standaarden voor klantinteracties

standard_family: nvt
